apiVersion: v1
kind: Service
metadata:
  name: fraud-service
  labels:
    app: fraud-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: fraud-service 