apiVersion: v1
kind: Service
metadata:
  name: medical-service
  namespace: medical-only
  labels:
    app: medical-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: medical-service 