apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-service
  namespace: medical-only
  labels:
    app: medical-service
    version: v2.0
    model: clinical-modernbert
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medical-service
  template:
    metadata:
      labels:
        app: medical-service
        version: v2.0
        model: clinical-modernbert
    spec:
      containers:
      - name: medical-service
        image: medical-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: http
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        env:
        - name: LOG_LEVEL
          value: "INFO"
        - name: ENVIRONMENT
          value: "production"
        - name: MODEL_VERSION
          value: "Clinical ModernBERT v2.0"
        - name: ENABLE_DETAILED_LOGGING
          value: "true"
        - name: MAX_TEXT_LENGTH
          value: "2000"
        - name: MAX_SYMPTOMS
          value: "20" 